### PR TITLE
Simplify FileBytesStream::into_stream

### PR DESCRIPTION
**Pull request by lnicola**
This is simpler and might be a little faster.

@seanmonstar sorry for tagging you, but can you confirm that this is a good idea?

### CODE REVIEW

**Comment by seanmonstar** [comment]
Assuming it's using a non-blocking read (looks like it with `tokio::fs::File`), this should be fine!

**Comment by lnicola** [comment]
@seanmonstar Thanks! Since you're here, I'll use the opportunity to ask another question. [This file](https://github.com/stephank/hyper-staticfile/blob/c2d73ea41b86ca2941fd3479090b8080fcb46a37/src/util/file_bytes_stream.rs) uses a pattern of reading into a buffer, then turning it into `Bytes`.

Is that the best possible approach? I thought it might be better to:

 - store a `BytesMut` 
 - read into the buffer
 - copy the data into the `BytesMut` using `BytesMut::extend`
 - Use `BytesMut::split` or `BytesMut::split_at` and pass the first chunk to `hyper`

My idea here is that it might save up on some allocations. Does it make sense? Am I completely wrong in how `Bytes` is supposed to be used?

I tried it and it was perhaps a little faster, but nothing impressive. But the extra copy seems like a bad thing. I also tried another approach:

- allocate a large `BytesMut`
- use `BytesMut::set_len` to set its length to its capacity
- pass that to `poll_read`
- use `BytesMut::split_at` and send the chunk that was read

This was faster, but I couldn't make it work -- the server closed the connection before the end of the file. But I now realize that I might have gotten something wrong, though.

For context, `futurs-fs` was [a lot faster](https://github.com/seanmonstar/futures-fs/issues/3), but that could also be a `tokio` scheduler or OS regression.

**Comment by seanmonstar** [comment]
- The use of a `BytesMut` and then splitting off can help reduce copies, sure.
- *Likely* the fast part of futures-fs is it's usage of the file system block size to determine how big a buffer to use in the first place.

**Comment by lnicola** [comment]
>     * The use of a `BytesMut` and then splitting off can help reduce copies, sure.

So my last variant (passing a `BytesMut` into `poll_read`) is reasonable, assuming I can make it work?
  
>     * _Likely_ the fast part of futures-fs is it's usage of the file system block size to determine how big a buffer to use in the first place.

I'm getting 55 MB/s (vs. 88 MB/s) with the default 8 KB buffer and 102 MB/s (vs. 175 MB/s) with the 128 KB one on the same system (but with a newer kernel and `tokio 0.2`). That's quite a difference.

**Comment by stephank** [comment]
Thanks for looking into this!

I didn't realize the `stream` feature was a default feature now. The piece of code here is a leftover from hyper 0.13 alphas, when `wrap_stream` was behind a an `unstable_stream` feature flag. So we can definitely remove it.

As for buffer sizes, the current 8 KiB may just have been a random guess by me. It definitely looks like it's halving speed here too. Increasing the buffer size, macOS at least is actually giving us 16 KiB at a time. (And buffer sizes above that don't matter.)

From what I understand, the way you intend to optimize with BytesMut is by not having to allocate on every read, but once every X reads? So for example, before each read, if capacity is below 16 KIB, extend capacity back up to 128 KiB, and then we can do X reads without allocation. That sounds cool, and I'm curious what it'll do for performance. (Maybe you can also detect the lower threshold by storing the highest seen return value from `poll_read`?)

The only worry I have is that we may end up making requests too heavy in memory usage. I'm not sure what kind of limits Hyper / Tokio put on max concurrency that could make this trouble.

**Comment by lnicola** [comment]
Regarding the buffer sizes, I actually made them configurable (which won't be too intrusive), but then got side-tracked with this. I was seeing about 2-3x worse performance than in my older measurements, so there might some room for improvement.

My idea with `BytesMut` was to use it as a queue: read directly to it, split a chunk and pass it to `hyper`. At some point that chunk would be reclaimed, freeing memory in the buffer. But I'm not sure whether it works like that or it ends up allocating, and it's not obvious to me from the implementation.

There's also the question of what happens when the disk is faster than the network. `hyper` uses an `mpsc` channel with no extra buffering, so we should only get one chunk at a time. There's some potential in keeping 1-2 chunks.

**Comment by stephank** [comment]
I'm trying to figure this out as well.

It looks like `Bytes` (and `BytesMut`) are either `KIND_VEC` owning a Vec directly or `KIND_ARC` pointing to an internal `struct Shared` that holds a reference counted Vec. Both are always contiguous chunks of memory. (The `BufMut` trait does allow non-contiguous backing, though I don't know what other crates are out there that would provide this.)

What's interesting is the `BytesMut::reserve` implementation. I think, at the time we reach buffer capacity and need more space, we'll always be a `KIND_ARC`, so we'd start here: https://github.com/tokio-rs/bytes/blob/8ae3bb2104fda9a02d55ac5635974ca1b5a49ebb/src/bytes_mut.rs#L578

It does try to reclaim space if it's the sole reference, but otherwise essentially creates a new `BytesMut` for the requested size. (Plus copying whatever's in the buffer already, but it'll always be empty in our case.)

You could see the reclaiming as a very limited kind of ring buffer, I guess? Anything more fancy would also mean we'd have to more carefully reason about the edge cases for memory usage and performance.

I do wonder how often it can reclaim in practice / how long Hyper holds on to buffers. But even the worst case does already mean, with a 128 KiB buffer and 16 KiB reads, you're only reallocating every 8 reads, which is nice.

Pseudo code of what I have in mind:

```
// in `poll_next`
if self.buf.capacity() < self.read_size {  // `read_size` can start at 0
  self.buf.reserve(self.buf_size); // `buf_size` is configurable by user.
}
match self.file.poll_read(cx, self.buf.bytes_mut()) {
  Ready(Ok(size)) => {
    self.read_size = max(self.read_size, size);
    Ready(Some(Ok(self.buf.split())))
  },
  // ...
}
```

**Comment by lnicola** [comment]
I'll try to implement something similar to that. It's going to be more awkward because you can't read into an empty `BytesMut`, so `reserve` won't be enough. I noticed that `tokio::fs` only seems to read 16 KB from my file, even with a larger buffer size, not sure why. Also, my server uses 100% and the speeds are pretty noisy, This seems a bit excessive.

Maybe we should figure this out in another PR and focus on the stream change here? That's hopefully easier to get through.

**Comment by lnicola** [comment]
For the record, the 16 KB limit comes from https://github.com/tokio-rs/tokio/blob/master/tokio/src/io/blocking.rs#L29.

**Pull request merged**
